### PR TITLE
[eslint-plugin] fix stylex/valid-styles false positives for member expressions 

### LINKED ISSUE #1520: ESLint: stylex/valid-styles reports false positives for function parameter references
### Describe the issue

`stylex/valid-styles` reports false positives for function parameter references in stylex.create arrow functions

The valid-styles rule flags `props.xxx` references inside stylex.create arrow functions as invalid values, even though StyleX compiles these into CSS variables at build time.

### Expected behavior

The rule correctly validates static entries but should allow values inside arrow function bodies in stylex.create, since these are dynamic parameters that StyleX handles at compile time. The function's type annotation already constrains the value — the ESLint rule shouldn't duplicate that check with a much narrower set of allowed values.

This affects all CSS properties where a function parameter is used as the value: `backgroundColor`, `color`, `transitionDelay`, `animationDelay`, `boxShadow`, etc. It also affects nested pseudo-class objects like `":hover": props.glowColor`.

### Steps to reproduce

```tsx
const styles = stylex.create({
  badge: (props: { badgeColor: string }) => ({
    backgroundColor: props.badgeColor, // ❌ "backgroundColor value must be one of: ..."
  }),
});
```

### Test case

_No response_

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by skovhus**
## What changed / motivation ?

The valid-styles rule only checked for Identifier nodes when skipping validation of arrow function parameters. MemberExpression nodes like props.badgeColor were not recognized, causing false positives. This adds a check that walks up the object chain of MemberExpressions to find the root identifier and skips validation when it maps to a function argument.

## Linked PR/Issues

Fixes #1520

## Additional Context

Screenshots, Tests, Anything Else

## Pre-flight checklist

- [x] I have read the contributing guidelines
      [Contribution Guidelines](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md)
- [x] Performed a self-review of my code

### CODE REVIEW

File: packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-styles-test.js [hunk 1]
```diff
@@ -881,6 +903,26 @@ eslintTester.run('stylex-valid-styles', rule.default, {
         });
       `,
     },
+    {
+      code: `
+        import * as stylex from '@stylexjs/stylex';
+        const styles = stylex.create({
+          foo: {
+            outlineOffset: 2,
```
Comment (skovhus) [inline packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-styles-test.js:911]: This was added by mistake.

**Comment by skovhus** [comment]
@mellyeliu seems like this caused CI to fails. Not sure why this was able to merge, maybe we need a merge status check for `tests / packages`?

File: packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-styles-test.js (hunk 1 above)
Comment (skovhus) [reply packages/@stylexjs/eslint-plugin/__tests__/stylex-valid-styles-test.js:911]: Fix is in https://github.com/facebook/stylex/pull/1523
