### PR TITLE
fix: Properly parse multi-value shorthand with slash

### LINKED ISSUE #730: Detect `/` within values of a multi-value `borderRadius` shorthand
NOTE: This is a very specific, edge-case bug.

When in `styleResolution: 'legacy-expand-shorthands'`, we expand shorthand CSS properties into their constituent longhand properties. This includes `borderRadius`.

However, when splitting `borderRadius`, we treat a space separation to imply the next direction. This misses the edge-case that `1px / 2px` is a valid value for a single corder when used in a `border-radius`.

e.g.
```ts
borderRadius: '1px / 2px 3px 4px 5px'
```

should be split into:

```ts
borderStartStartRadius: '1px 2px',
borderStartEndRadius: '1px 3px',
borderEndEndRadius: '1px 4px',
borderEndStartRadius: '1px 4px',
```

### PR DESCRIPTION
**Pull request by yasuhiro-yamamoto**
## What changed / motivation ?

Fixed the expansion handling of border-radius shorthand values containing the '/' separator.

## Linked PR/Issues

Fixes #730 

## Additional Context

- Modified the splitValue function to handle nodes containing '/' by merging them with adjacent nodes
- Example: '1px / 2px' is now correctly processed as borderStartStartRadius: '1px / 2px'
- Added test cases in packages/shared/__tests__/split-value-test.js

## Pre-flight checklist

- [x] I have read the contributing guidelines
      [Contribution Guidelines](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md)
- [x] Performed a self-review of my code

### CODE REVIEW

File: packages/shared/__tests__/split-value-test.js [hunk 1]
```diff
@@ -44,4 +44,13 @@ describe('Ensure CSS values are split correctly', () => {
...
+
+  test('Splits a string of values with slash notation appropriately.', () => {
+    expect(splitValue('1px/2px 3px 4px 5px')).toEqual([
+      '1px/2px',
+      '3px',
+      '4px',
+      '5px',
+    ]);
+  });
 });
```
Comment (nmn) [inline packages/shared/__tests__/split-value-test.js:56]: This is not how border-radius values are expanded. The correct expansion should be:


```suggestion

  test('Splits a string of values with slash notation appropriately.', () => {
    expect(splitValue('1px/2px 3px 4px 5px')).toEqual([
      '1px 2px',
      '1px 3px',
      '1px 4px',
      '1px 5px',
    ]);
  });
});
```

See https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius
which mentions:

```css
border-radius: 4px 3px 6px / 2px 4px;

/* It is equivalent to: */
border-top-left-radius: 4px 2px;
border-top-right-radius: 3px 4px;
border-bottom-right-radius: 6px 2px;
border-bottom-left-radius: 3px 4px;
```

**Review by nmn — CHANGES_REQUESTED** [review]
Thanks for trying to fix this edge case, but the logic isn't quite right.

(Note: also, this code path is only used if you use the `legacy-expand-shorthands` configuration which should not be needed in the vast majority of use-cases.)

File: packages/shared/__tests__/split-value-test.js (hunk 1 above)
Comment (yasuhiro-yamamoto) [reply packages/shared/__tests__/split-value-test.js:56]: I misunderstood the usage of `/` in `border-radius`. I will review the specification and correct the code accordingly.

**Comment by yasuhiro-yamamoto** [comment]
@nmn I've revised the expansion logic for cases involving '/' and corrected the code. Additionally, I've updated the `splitValue` function to accept an optional argument, and explicitly handle processing specific to border-radius within the code.

**Review by nmn — APPROVED** [review]
LGTM.

**Comment by nmn** [comment]
Will merge this PR after doing more testing as this code primarily affects internal code.

**Review by mellyeliu — APPROVED** [review]
