### PR TITLE
[eslint-plugin] fix isNumber utils and isMathCall utils

### LINKED ISSUE #1134: `isNumber` check broken in valid-styles rule
### Describe the issue

Rule always returns true due to bad ternary checks. This leads to a vast majority of length properties having improper style validation

### Steps to reproduce

Add invalid css to any length properties

### PR DESCRIPTION
**Pull request by mellyeliu**
Fixes #1134

- `isNumber`  previously returned `undefined` due to an improper ternary check, causing them to always pass. rewrote using basic if/else for readability
- `isMathCall` logic was error prone and overly strict, required all Math.*() arguments to be recursively valid numbers, false negatives and circular dependencies
- Meaning every length css property (or any property with an `isNumber` check) was always valid as per the linter
- Fixed logic to correctly return a `RuleResponse` when a value is invalid.
- Also allowed `MemberExpression` and `CallExpression` nodes to broadly allow functions/vars as valid number values (we could make this stricter, but they're not reliably statically analyzable, and I suspect it'll add a ton of volume to the internal eslint errors, and it's still safer than before (checking nothing))
- This rule is in a pretty bad shape so this is one of many iterations

### CODE REVIEW

File: packages/@stylexjs/eslint-plugin/src/stylex-valid-styles.js [hunk 1]
```diff
@@ -1938,7 +1938,7 @@ const CSSProperties = {
   insetInlineStart: isStringOrNumber,
   insetInlineEnd: isStringOrNumber,
 
-  height: isStringOrNumber,
+  height: width,
```
Comment (ezzak) [inline packages/@stylexjs/eslint-plugin/src/stylex-valid-styles.js:1941]: Maybe rename to `widthOrHeight` or if you have a more appropriate name.

Comment (mellyeliu) [reply packages/@stylexjs/eslint-plugin/src/stylex-valid-styles.js:1941]: need to do an overhaul of the var naming in this whole file...  

will do in follow up rewrite, many properties are assigned rules with unrelated naming
