### PR TITLE
[babel-plugin] Fix pseudo-element + pseudo-class selector ordering

### LINKED ISSUE #1473: Pseudo-elements don't work with pseudoclasses
We enforce top-level pseudo-elements, but given something like so:

```js
const styles = stylex.create({
    foo: {
    "::before": {
      content: '"✓"',
      color: {
        default: 'yellow',
        ':hover': 'red'
      },
   }
})
```

The outputted CSS is as follows, which is invalid, as pseudo-elements must after at the end of the selector.
```css
.x1qdmp1q::before:hover{color:red}
```

### PR DESCRIPTION
**Pull request by skovhus**
## What changed / motivation ?

Pseudo-elements like `::before` and `::after` must appear at the end of a CSS selector. When combining pseudo-elements with pseudo-class conditions (e.g. `:hover`, `:active`), StyleX generated invalid selectors like `.x123::after:hover` which browsers silently discard. The fix reorders them to `.x123:hover::after`.

## Linked PR/Issues

Fixes #1473

## Additional Context

n/a

## Pre-flight checklist

- [x] I have read the contributing guidelines
      [Contribution Guidelines](https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md)
- [x] Performed a self-review of my code

### CODE REVIEW

File: packages/@stylexjs/babel-plugin/__tests__/transform-stylex-create-test.js [hunk 1]
```diff
@@ -2389,6 +2388,36 @@ describe('@stylexjs/babel-plugin', () => {
...
+                    ':active': '0 0 0 1px darkblue',
+                  },
+                },
+              },
+            });
+          `);
+
+          // Pseudo-classes (:hover, :active) must come before the
+          // pseudo-element (::after) in the selector for valid CSS.
+          const rules = metadata.stylex.map(([className, { ltr }]) => ltr);
```
Comment (skovhus) [inline packages/@stylexjs/babel-plugin/__tests__/transform-stylex-create-test.js]:
```suggestion
          const rules = metadata.stylex.map(([_className, { ltr }]) => ltr);
```

File: packages/@stylexjs/babel-plugin/src/shared/utils/generate-css-rule.js [hunk 2]
```diff
@@ -29,7 +29,12 @@ function buildNestedCSSRule(
   atRules: $ReadOnlyArray<string>,
   constRules: $ReadOnlyArray<string>,
 ): string {
-  const pseudo = pseudos.filter((p) => p !== '::thumb').join('');
+  const filteredPseudos = pseudos.filter((p) => p !== '::thumb');
+  // Pseudo-elements (::before, ::after, etc.) must come after pseudo-classes
+  // in the selector. e.g. `.class:hover::before` not `.class::before:hover`
+  const pseudoClasses = filteredPseudos.filter((p) => !p.startsWith('::'));
+  const pseudoElements = filteredPseudos.filter((p) => p.startsWith('::'));
+  const pseudo = [...pseudoClasses, ...pseudoElements].join('');
```
Comment (Dwlad90) [inline packages/@stylexjs/babel-plugin/src/shared/utils/generate-css-rule.js]: A more optimized solution with a single-pass loop

```suggestion
  // Pseudo-elements (::before, ::after, etc.) must come after pseudo-classes
  // in the selector. e.g. `.class:hover::before` not `.class::before:hover`
const { classes, elements } = pseudos.reduce((acc, p) => {
  if (p === '::thumb') return acc;

  if (p.startsWith('::')) {
    acc.elements += p;
  } else {
    acc.classes += p;
  }
  return acc;
}, { classes: '', elements: '' });

const pseudo = classes + elements;
```

Comment (skovhus) [reply packages/@stylexjs/babel-plugin/src/shared/utils/generate-css-rule.js]: Thanks!

**Comment by skovhus** [comment]
@mellyeliu thanks for wrapping this up

**Review by mellyeliu — APPROVED** [review]

**Comment by mellyeliu** [comment]
@skovhus thanks for putting up this fix! sorry for the delay
