### PR TITLE
fix: fix eslint sort-keys handling nested properties

### LINKED ISSUE #391: `sort-keys` comparing `default` with parent property
### Describe the issue

The new `sort-keys` eslint rule seems to give some unexpected errors, suggesting it's comparing the inner keys with parent keys.

image

### Expected behavior

It's expected that the test case below is valid, however it errors with the message

> StyleX property key "default" should be above "maxWidth".

### Steps to reproduce

`@stylexjs/eslint-plugin@0.5.1`

- Add new test case in `packages/eslint-plugin/__tests__/stylex-sort-keys-test.js` with the below test case as a valid case
- Run `npm run test -w @stylexjs/eslint-plugin` and observe test failure with message `StyleX property key "default" should be above "maxWidth"`

### Test case

```js
      import stylex from 'stylex';
      const styles = stylex.create({
        nav: {
          maxWidth: {
            default: "1080px",
            ["@media (min-width: 2000px)"]: "calc((1080 / 24) * 1rem)"
          },
          paddingVertical: 0,
        },
      });
```

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by QingqiShi**
## What changed / motivation ?

Fix a bug where the `sort-keys` rule is giving errors for nested keys, comparing them to the parent keys.

## Linked PR/Issues

Fixes #391 

## Additional Context

I *think* the issue here is that, after adding the outer object to the stack, subsequent nested objects are never actually pushed onto this stack, resulting in a stack that maintains only a single layer.

## Pre-flight checklist

- [x] I have read the contributing guidelines
      [Contribution Guidelines](./CONTRIBUTING.md)
- [x] Performed a self-review of my code

### CODE REVIEW

File: packages/eslint-plugin/src/stylex-sort-keys.js [hunk 1]
```diff
@@ -169,7 +169,7 @@ const stylexSortKeys = {
           objectExpressionNestingLevel++;
         }
 
-        if (objectExpressionNestingLevel === 1) {
+        if (objectExpressionNestingLevel > 0) {
```
Comment (nedjulius) [inline packages/eslint-plugin/src/stylex-sort-keys.js:172]: nice catch! thanks for fixing

**Review by nmn — APPROVED** [review]
nodding-meme
