### PR TITLE
fix: Remove non-standard CSS properties

### LINKED ISSUE #604: Remove non-standard CSS properties from types
### Describe the issue

StyleXCSSTypes contains non-standard CSS property types, for example:

```
  borderStart?: all | border,
  borderStartColor?: all | borderLeftColor,
  borderStartStyle?: all | borderLeftStyle,
  borderStartWidth?: all | borderLeftWidth,
```

### Expected behavior

No non-standard CSS logical properties.

### Steps to reproduce

.

### Test case

.

### Additional comments

.

### PR DESCRIPTION
**Pull request by nmn**
Fixes #604

### CODE REVIEW

File: packages/eslint-plugin/src/stylex-valid-styles.js [hunk 1]
```diff
@@ -592,20 +592,9 @@ const borderImage = makeUnionRule(
   isString,
   borderImageRepeat,
 );
-// const borderInlineEnd = makeUnionRule(borderWidth, borderStyle, color);
```
Comment (necolas) [inline packages/eslint-plugin/src/stylex-valid-styles.js:595]: Are these already declared elsewhere?

File: packages/eslint-plugin/src/stylex-valid-styles.js [hunk 2]
```diff
@@ -592,20 +592,9 @@ const borderImage = makeUnionRule(
...
-// const borderInlineEndStyle = borderStyle;
-// const borderInlineEndWidth = borderWidth;
-// const borderInlineStart = makeUnionRule(borderWidth, borderStyle, color);
-// const borderInlineStartColor = color;
-// const borderInlineStartStyle = borderStyle;
-// const borderInlineStartWidth = borderWidth;
 const borderLeftColor = color;
 const borderLeftStyle = brStyle;
 const borderLeftWidth = borderWidth;
-const borderRightColor = color;
```
Comment (necolas) [inline packages/eslint-plugin/src/stylex-valid-styles.js:606]: Are these meant to be deleted?

File: packages/eslint-plugin/src/stylex-valid-styles.js (hunk 1 above)
Comment (nmn) [reply packages/eslint-plugin/src/stylex-valid-styles.js:595]: Border short hands are intentionally disallowed right now.

File: packages/eslint-plugin/src/stylex-valid-styles.js (hunk 2 above)
Comment (nmn) [reply packages/eslint-plugin/src/stylex-valid-styles.js:606]: Yeah, `borderRightColor` references `color` directly instead.

File: packages/eslint-plugin/src/stylex-valid-styles.js (hunk 1 above)
Comment (necolas) [reply packages/eslint-plugin/src/stylex-valid-styles.js:595]: Oh yes, sorry I misread those
