### PR TITLE
fix: cli should rewrite the aliases

### LINKED ISSUE #846: [CLI] Rewrite aliases when compiling a folder
It is common to use the `@/` alias in Next.js. When using the CLI, the tsconfig is usually changed to update the alias to point to `source` instead of `src`.

Today, this means that any `@/` import in the `src/` folder will resolve to the uncompiled files in `source` and cause runtime errors.

We should rewrite aliases as part of the CLI to avoid dealing with this problem manually.

referece: #844

### PR DESCRIPTION
**Pull request by nmn**
## What changed / motivation ?

The CLI will now rewrite imports based on the `aliases` that are passed into `stylexConfig`.

Resolves #846 

### Side note:

It might make sense to extract some of the utilities that were copied from the `babel-plugin` to a separate `utils` package for such use-cases.

### CODE REVIEW

File: packages/cli/src/config.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ export type CliConfig = {
   babelPluginsPost?: $ReadOnlyArray<any>,
   modules_EXPERIMENTAL: $ReadOnlyArray<ModuleType>,
   useCSSLayers?: boolean,
-  styleXConfig?: { +[string]: mixed },
+  styleXConfig?: StyleXOptions,
```
Comment (Jta26) [inline packages/cli/src/config.js:27]: nit: match naming

File: packages/cli/src/plugins.js [hunk 2]
```diff
@@ -116,3 +121,143 @@ export const createModuleImportModifierPlugin = (
...
+        return moduleResolve(possiblePath, url.pathToFileURL(sourceFilePath))
+          .pathname;
+      } catch {
+        continue;
+      }
+    }
+  }
+  // Failed to resolve the file path
+  return null;
+};
```
Comment (Jta26) [inline packages/cli/src/plugins.js:232]: Did you intend to use the newly exported functions from the babel plugin here, or is there a special edge case that makes them incompatible?

File: packages/cli/src/plugins.js [hunk 3]
```diff
@@ -116,3 +121,143 @@ export const createModuleImportModifierPlugin = (
...
+  filename.endsWith(`${allowedSuffix}.jsx`) ||
+  filename.endsWith(`${allowedSuffix}.mjs`) ||
+  filename.endsWith(`${allowedSuffix}.cjs`) ||
+  filename.endsWith(allowedSuffix);
+
+const EXTENSIONS = ['.js', '.ts', '.tsx', '.jsx', '.mjs', '.cjs'];
+const filePathResolver = (
+  relativeFilePath: string,
+  sourceFilePath: string,
+  aliases: $ReadOnly<{ [string]: $ReadOnlyArray<string> }>,
```
Comment (Jta26) [inline packages/cli/src/plugins.js:202]: Are the aliases in here going to have to be something you specify in the `stylex.json` where you have to explicitly tell the CLI where the aliases resolve to?

**Review by Jta26 — APPROVED** [review]
Looks good, just a few questions

File: packages/cli/src/plugins.js [hunk 4]
```diff
@@ -116,3 +121,143 @@ export const createModuleImportModifierPlugin = (
...
+            },
+          });
+        },
+      },
+    },
+  };
+};
+
+const matchesFileSuffix = (allowedSuffix: string) => (filename: string) =>
+  filename.endsWith(`${allowedSuffix}.js`) ||
```
Comment (mellyeliu) [inline packages/cli/src/plugins.js:190]: can we use a loop ie. `EXTENSIONS.some(ext => filename.endsWith(`${allowedSuffix}${ext}`))`

**Review by mellyeliu — APPROVED** [review]

File: packages/cli/src/plugins.js (hunk 2 above)
Comment (nmn) [reply packages/cli/src/plugins.js:232]: The Babel plugin is compiled into a single bundle which makes using the individual exports impossible. I will need to refactor some of these utility functions to a separate package.

For now I just copied the relevant bits.

File: packages/cli/src/plugins.js (hunk 3 above)
Comment (nmn) [reply packages/cli/src/plugins.js:202]: Yes. This is already the case in the `cli-example`.

Comment (nmn) [reply packages/cli/src/plugins.js:202]: However, there is a PR up right now which discovers aliases automatically. That PR will need to be updated to do that work in the CLI as well.

It might also make sense to move alias rewriting to the main StyleX plugin as it already has all the relevant logic. (This might be the right thing to do actually....)
