### PR TITLE
Remove legacy RTL flipping of boxShadow, cursor, textShadow values

### LINKED ISSUE #1120: box-shadow rules with space gets detected as LTR != RTL
### Describe the issue

I have a rule like this:

```
boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
```

The key is on the space after the comma.

It generates the following CSS:

```
html:not([dir='rtl']) .boxShadow-xalsa2k{box-shadow:0 10px 15px -3px rgb(0 0 0 / .1),0 4px 6px -4px rgb(0 0 0 / .1)}
html[dir='rtl'] .boxShadow-xalsa2k{box-shadow:0 10px 15px -3px rgb(0 0 0 / .1), 0 4px 6px -4px rgb(0 0 0 / .1)}
```

Debug lines:

```
  cssLTR: .boxShadow-xalsa2k{box-shadow:0 10px 15px -3px rgb(0 0 0 / .1),0 4px 6px -4px rgb(0 0 0 / .1)}
  cssRTL: .boxShadow-xalsa2k{box-shadow:0 10px 15px -3px rgb(0 0 0 / .1), 0 4px 6px -4px rgb(0 0 0 / .1)}
  cssRTL === null: false
  cssRTL === cssLTR: false
  priority: 3000
  🚨 RTL differs from LTR!
  LTR length: 94
  RTL length: 95
```

### Expected behavior

Should be detected correctly.

### Steps to reproduce

Add the rule

### Test case

_No response_

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by necolas**
Cartesian coordinates (x,y) and cardinal directions (N,E,S,W) should not be flipped for RTL writing directions. This behavior is neither part of the W3C standards nor common sense.

The behavior is preserved (but disabled by default) with a new feature flag - enableLegacyLogicalValues - while Meta migrates internal code off this behavior.

Fix #1120

### CODE REVIEW

File: packages/@stylexjs/babel-plugin/src/shared/common-types.js [hunk 1]
```diff
@@ -52,6 +52,7 @@ export type StyleXOptions = $ReadOnly<{
   enableDebugDataProp?: ?boolean,
   enableDevClassNames?: ?boolean,
   enableFontSizePxToRem?: ?boolean,
+  enableLegacyLogicalValues?: ?boolean,
```
Comment (necolas) [inline packages/@stylexjs/babel-plugin/src/shared/common-types.js]: Open to suggestions for a better flag name

Comment (mellyeliu) [reply packages/@stylexjs/babel-plugin/src/shared/common-types.js]: `enableLegacyRTLValues`? 

difficult to encapsulate the specificity of this flag with 3 words lol

Comment (necolas) [reply packages/@stylexjs/babel-plugin/src/shared/common-types.js]: Changed it to `enableLegacyValueFlipping`
